### ISSUE TITLE
Add functions of BOM model in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#148]
A created a new file named BOM_functions_1 in JavaScript_Advance and add the following:

- Window History
- Window Navigator
- JavaScript Popup Boxes

Create .md and .js both files as we are shifting to Docsify

**Comment by eLeontev** [comment]
I will take care

**Comment by eLeontev** [comment]
@Swap76 do you agree to place popup boxes in separate file since they are not related to navigator?
my proposal: 
A created a new file named BOM_functions_1 in JavaScript_Advance and add the following:
Window History
Window Navigator
A created a new file named popupBoxes in JavaScript_Advance and add the following:
JavaScript Popup Boxes


Create .md and .js both files as we are shifting to Docsify

**Comment by Swap76** [comment]
@eLeontev Cool I will be reviewing the PRs
